GET http://localhost:3001/post/all/

###

POST http://localhost:3001/post/new/
Content-Type: application/json

{
    "title": "Blog post 3",
    "content": "post 3 content",
    "author": "65a9df783e1e52000ab0d82d"

}

###

GET http://localhost:3001/post/my-posts/

###

DELETE http://localhost:3001/post/delete/65aa981ebab04ad5baa8100f