GET http://localhost:3001/post/all-posts/

###

POST http://localhost:3001/post/new/
Content-Type: application/json

{
    "title": "Blog post 1",
    "content": "post 1 content",
    "author": "65a9df783e1e52000ab0d82d"

}

###